version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: legendary_postgres
    environment:
      POSTGRES_DB: legendary_growth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: legendary_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@legendary.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data:
